import groovy.json.JsonSlurperClassic
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'windows' }
  environment {
    appName = "variable" 
  }
  stages {
    stage("build") {
      steps {
        sh "echo 'Hello World'"
      }
    }
  }
}  

