import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'main' }
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {
          script {			
            sh '''#!/bin/bash
                 echo "hello world" 
         '''
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
            sh '''#!/bin/bash
                 echo "fase always" 
         '''
      }
      success {
            sh '''#!/bin/bash
                 echo "fase success" 
         '''
        }

      failure {
            sh '''#!/bin/bash
                 echo "fase failure" 
         '''
      }
      
  }
}  

